version: '3.4'
services:
  publisher_api:
    build:
      context: ./publisher-api
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - DEV_PLATFORM=DOCKER
    volumes:
      - ./publisher-api/src:/app/src
      - /app/node_modules
    ports:
      # forwarding: left side local host, right side docker container
      - 5000:5000
      - 9229:9229 # for debugging
