# Use the official Node.js 20 Alpine image as the base image
FROM node:20-alpine AS subscriber-api

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies 
RUN npm i

#--only=production
COPY . .
# Build steps
# 9229 is the default port for the V8 inspector 
EXPOSE ${PORT} 9229 
CMD ["npm", "run", "start:dev"]
