# Use a base image with Node.js
FROM node:20-alpine AS subscriber-client

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm i

# Copy the rest of the app files
COPY . .

# Expose the port 3001
EXPOSE 3001

# Build the React app 
CMD [ "npm", "run", "dev" ] 